### ISSUE TITLE
Typing start bug

### ISSUE THREAD

**Issue by G3bE** [itsVale/Shitcord#10]
### Describe the Bug

When typing in a direct message channel with the bot it gets a KeyError because the event model for typing start tries to get a guild_id without `get('guild_id')`. Same happens for message delete.

### To Reproduce

_Steps to reproduce the behaviour:_

  1. Create a simple bot that just connects to the gateway, no event method needed
  2. Open a DM channel with your bot
  3. Start typing or delete an already existing message

### Screenshots

No screenshots but a nice error:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ws4py/websocket.py", line 528, in run
    if not self.once():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ws4py/websocket.py", line 410, in once
    if not self.process(self.buf[:requested]):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ws4py/websocket.py", line 480, in process
    self.received_message(s.message)
  File "/Users/nikolas/PycharmProjects/Shitcord-dev-gateway/shitcord/gateway/connector.py", line 79, in received_message
    self.fire_event(event.lower(), data)
  File "/Users/nikolas/PycharmProjects/Shitcord-dev-gateway/shitcord/gateway/connector.py", line 82, in fire_event
    data = parser.parse_data(name, data)
  File "/Users/nikolas/PycharmProjects/Shitcord-dev-gateway/shitcord/events/parser.py", line 40, in parse_data
    return parsers[event].parse(data)
  File "/Users/nikolas/PycharmProjects/Shitcord-dev-gateway/shitcord/events/parsers.py", line 15, in parse
    return self.model(data)
  File "/Users/nikolas/PycharmProjects/Shitcord-dev-gateway/shitcord/events/event_models.py", line 40, in __init__
    self.guild = data['guild_id']
KeyError: 'guild_id'
2018-10-27T11:07:34Z <Greenlet "Greenlet-0" at 0x10b6df9d8: <bound method WebSocket.run of <shitcord.gateway.connector.GatewayClient object at 0x10b990dd8>>> failed with KeyError

```

**Comment by itsVale** [comment]
I'm pretty sure that's an error you caused yourself when creating the models lol. Gotta fix this soon. Thanks for the information!

**Comment by G3bE** [comment]
Error came from events/event_models.py wich is not by me. (╯°□°）╯︵ ┻━┻

**Comment by itsVale** [comment]
This just references the Channel model you created. You access guild_id in any case though in DM channels, like you describe, this is not given and causes a KeyError when trying to access it.

**Comment by byWambo** [comment]
Fixed
