### ISSUE TITLE
trio BrokenResourceError

### ISSUE THREAD

**Issue by G3bE** [itsVale/Shitcord#29]
# Bug Rport

### Describe the Bug

_A clear and concise description of what the bug is._

When I try to use the example from README.md I get this error:
```
[DEBUG] 2019-01-08 22:31:09,435 - shitcord.http.http:82 - Performing request to bucket ('POST', '/channels/494188636791767040/messages') with headers {'User-Agent': 'DiscordBot (https://github.com/itsVale/Shitcord, v0.0.2b) / Python 3.6.8', 'Authorization': 'Bot That's my token i deleted it'}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_ssl.py", line 455, in _retry
    ret = fn(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nikolas/PycharmProjects/Shitcord-async/test.py", line 25, in <module>
    trio.run(spam_the_api, channel_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_core/_run.py", line 1337, in run
    raise runner.main_task_outcome.error
  File "/Users/nikolas/PycharmProjects/Shitcord-async/test.py", line 21, in spam_the_api
    await http.make_request(Endpoints.CREATE_MESSAGE, dict(channel=channel_id), json=json)
  File "/Users/nikolas/PycharmProjects/Shitcord-async/shitcord/http/http.py", line 89, in make_request
    response = await self._session.request(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/asks/sessions.py", line 170, in request
    connection_timeout, self._grab_connection, url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/asks/utils.py", line 15, in timeout_manager
    return (await coro(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/asks/sessions.py", line 361, in _grab_connection
    sock = await self._make_connection(host_loc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/asks/sessions.py", line 335, in _make_connection
    sock, port = await self._connect(host_loc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/asks/sessions.py", line 103, in _connect
    (host, int(port))), port
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/asks/sessions.py", line 81, in _open_connection_https
    source_addr=self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/multio/_event_loop_wrappers.py", line 30, in trio_open_connection
    await sock.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_ssl.py", line 602, in do_handshake
    await self._handshook.ensure(checkpoint=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_ssl.py", line 224, in ensure
    await self._afn(*self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_ssl.py", line 568, in _do_handshake
    await self._retry(self._ssl_object.do_handshake)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trio/_ssl.py", line 462, in _retry
    raise _core.BrokenResourceError from exc
trio.BrokenResourceError
```

### To Reproduce

_Steps to reproduce the behaviour:_

  1. Install shitcord async via pip or clone the repo
  2. Create a new python file
  3. Copy paste the example from README.md
  4. Insert a valid token & channel ID
  5. Try to start the client

### Expected behaviour

_A clear and concise description of what you expected to happen._

The script would spam to the given channel.

### Specifications

**Desktop (please complete the following information):**

  - Hardware: **MacBookAir 6,1**
  - OS: **macOS 10.14.2**
  - Version: **Shitcord 0.0.2b** and **Python 3.7**

**Comment by itsVale** [comment]
Hello, thanks for your issue! The first thing that is a bit suspect is that your User-Agent (`DiscordBot (https://github.com/itsVale/Shitcord, v0.0.2b) / Python 3.6.8`) includes Python 3.6.8 while you denoted you're using Python 3.7 in the specifications. I'd suggest you try to resolve this first and see if it works then. If not, I'll do some further research this weekend.

**Comment by G3bE** [comment]
Yeah it works with python 3.7. PyCharm told me the wrong version.

**Comment by itsVale** [comment]
But this is strange though. Should actually work with lower Python versions too. I'll do some research about this issue. Until then, leave this issue open please.

**Comment by G3bE** [comment]
I now executed `Install Certificates.command` in my Python 3.6 directory in `Applications` and everything works fine!
